groups:
-  name: cpugroup
   rules:
   - alert: Cpu
     expr: node_load5 > 3.5
     for: 1m
     labels:
       severity: critical
     annotations:
       description: "CPU High {{ $labels.instance }} / Job: {{ $labels.job }} / Value : {{ .Value }}"
