global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    cluster: swarm
    monitor: codelab-monitor
    replica: "1"
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
  dns_sd_configs:
  - names:
    - tasks.node-exporter
    refresh_interval: 30s
    type: A
    port: 9100
- job_name: docker
  static_configs:
  - targets:
    - 192.168.1.65:9323
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
  dns_sd_configs:
  - names:
    - tasks.cadvisor
    refresh_interval: 30s
    type: A
    port: 8080
- job_name: traefik
  static_configs:
  - targets:
    - traefik:81
  basic_auth:
    username: admin
    password: <secret>
